kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: sa-role-binding
   namespace: default
subjects:
 - kind: ServiceAccount
   name: sa-app01
   namespace: default
roleRef:
   kind: Role
   name: pod-reader-role
   apiGroup: rbac.authorization.k8s.io